name: country_map_info_app
description: "country_map_info_app project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  melos: ^6.1.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
