library;

export 'package:auto_route/auto_route.dart';
export 'package:bloc/bloc.dart';
export 'package:easy_localization/easy_localization.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:flutter_secure_storage/flutter_secure_storage.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:get_it/get_it.dart';
export 'package:injectable/injectable.dart';
export 'package:json_api/client.dart';
export 'package:json_api/routing.dart';
export 'package:loading_animation_widget/loading_animation_widget.dart';
// export 'package:material_dialogs/material_dialogs.dart';
export 'package:provider/provider.dart';
export 'package:rxdart/rxdart.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:toastification/toastification.dart';
export 'package:dio/dio.dart';


// common dependencies
export 'src/common_dependencies/duration_constants.dart';
export 'src/common_dependencies/enum.dart';
export 'src/common_dependencies/locale_constants.dart';
export 'src/common_dependencies/server_request_response.dart';
export 'src/common_dependencies/shared_preferences_keys.dart';
export 'src/common_dependencies/constants/server/url_constants.dart';
export 'src/common_dependencies/constants/server/url_details_constants.dart';

// core
export 'src/core/source/api/app_api_service.dart';
export 'src/core/source/api/client/base/rest_api_client.dart';
export 'src/core/bloc/app_bloc_observer.dart';
export 'src/core/bloc/base_bloc.dart';
export 'src/core/bloc/base_bloc_event.dart';
export 'src/core/bloc/base_bloc_state.dart';
export 'src/core/bloc/base_page_state.dart';
export 'src/core/bloc/common/common_bloc.dart';
export 'src/core/bloc/common/common_event.dart';
export 'src/core/bloc/common/common_state.dart';
export 'src/core/bloc/mixin/event_transformer_mixin.dart';
export 'src/core/config/build_config.dart';
export 'src/core/source/api/middleware/header_interceptor.dart';
export 'src/core/config/config.dart';
export 'src/core/config/log_config.dart';
export 'src/core/errors/base/app_exception.dart';
export 'src/core/errors/base/app_exception_wrapper.dart';
export 'src/core/errors/exception/uncaught/app_uncaught_exception.dart';
export 'src/core/errors/exception/validation/validation_exception.dart';
export 'src/core/errors/exception_handler/exception_handler.dart';
export 'src/core/errors/exception_handler/exception_message_mapper.dart';
export 'src/core/errors/remote/remote_exception.dart';
export 'src/core/errors/remote/server_error.dart';
export 'src/core/errors/remote/server_error_detail.dart';
export 'src/core/helper/function/function.dart';
export 'src/core/helper/stream/disposable_page.dart';
export 'src/core/helper/stream/dispose_bag.dart';
export 'src/core/helper/stream/stream_logger.dart';
export 'src/core/mapper/base/base_data_mapper.dart';
export 'src/core/mapper/language_code_data_mapper.dart';
export 'src/core/mixin/log_mixin.dart';
export 'src/core/modules/injection.dart';
export 'src/core/modules/injection_module.dart';
export 'src/core/source/preference/app_preference.dart';
export 'src/core/ui/app_color_extension.dart';
export 'src/core/ui/app_pallete.dart';
export 'src/core/ui/app_topology.dart';
export 'src/core/ui/device_constants.dart';
export 'src/core/ui/widget/custom_button.dart';
export 'src/core/usecases/base/base_use_case.dart';
export 'src/core/usecases/base/future/base_future_use_case.dart';
export 'src/core/usecases/base/io/base_input.dart';
export 'src/core/usecases/base/io/base_output.dart';
export 'src/core/usecases/base/stream/base_stream_use_case.dart';
export 'src/core/usecases/base/sync/base_sync_use_case.dart';
export 'src/core/util/extensions.dart';
export 'src/core/util/log_utils.dart';
export 'src/core/util/validation_utils.dart';
export 'src/core/util/view_utils.dart';
export 'src/core/source/api/middleware/connectivity_interceptor.dart';
export 'src/core/source/api/middleware/custom_log_interceptor.dart';
export 'src/core/errors/base/exception_mapper.dart';
export 'src/core/source/api/middleware/base_interceptor.dart';
export 'src/core/mapper/base_error_response_mapper/base_error_response_mapper.dart';
export 'src/core/mapper/base/base_success_response_mapper.dart';
export 'src/core/model/base_data/data_response.dart';
export 'src/core/model/typedef.dart';
export 'src/core/model/base_data/results_response.dart';
export 'src/core/mapper/base_success_response_mapper/data_json_array_response_mapper.dart';
export 'src/core/mapper/base_success_response_mapper/data_json_object_reponse_mapper.dart';
export 'src/core/mapper/base_success_response_mapper/json_array_response_mapper.dart';
export 'src/core/mapper/base_success_response_mapper/json_object_reponse_mapper.dart';
export 'src/core/mapper/base_success_response_mapper/results_json_array_response_mapper.dart';

export 'src/core/ui/widget/custom_scaffold.dart';
export 'src/core/ui/widget/custom_dialog.dart';
export 'src/core/ui/widget/popup_button.dart';
export 'src/core/ui/widget/custom_app_bar.dart';

export 'src/core/ui/resource/styles/app_themes.dart';
export 'src/core/ui/resource/dimens/app_dimen.dart';
export 'src/core/ui/resource/dimens/dimens.dart';
export 'src/core/ui/resource/styles/app_colors.dart';
export 'src/core/ui/resource/styles/app_text_styles.dart';

//routing
export 'src/routing/app_navigator.dart';
export 'src/routing/app_popup_info.dart';
export 'src/routing/app_route_info.dart';
