name: feature
description: "A Feature project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../infrastructure/core/
  app:
    path: ../app/

  json_annotation: ^4.8.1
  flutter_lints: ^5.0.0
  google_maps_flutter: ^2.10.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.3
  build_runner: ^2.4.11
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  auto_route_generator: ^9.0.0
  logging: ^1.2.0

flutter:
  uses-material-design: true


